version: "3"
services:

  invidious:
    image: quay.io/invidious/invidious:latest
    # image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    restart: unless-stopped
    ports:
      - "2839:2839"
    environment:
      INVIDIOUS_CONFIG: |
        db:
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
          dbname: invidious
        port: 2839
        host_binding: 0.0.0.0
        hsts: true
        disable_proxy: false
        pool_size: 100
        statistics_enabled: true
        registration_enabled: true
        login_enabled: true
        captcha_enabled: true
        enable_user_notifications: true
        channel_threads: 1
        full_refresh: false
        feed_threads: 1
        https_only: true
        jobs:
          clear_expired_items:
            enable: true
          refresh_channels:
            enable: true
          refresh_feeds:
            enable: true
        hmac_key: "chi8eiQuaiKaiGaabohV"
        default_user_preferences:
          quality: hd720
          local: true
          feed_menu: ["Trending"]
          default_home: Trending
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
